### ISSUE TITLE
Consider template() function to generate empty named lists for objects

### ISSUE THREAD

**Issue by cboettig** [cboettig/emld#10]
Just added a prototype of this method.  Returns a list object which I preview here using the yaml layout.   

```r
> template("contact", recursive = TRUE) %>% as.yaml() %>% cat()
```

```
individualName:
  salutation: {}
  givenName: {}
  surName: {}
organizationName: {}
positionName: {}
address:
  deliveryPoint: {}
  city: {}
  administrativeArea: {}
  postalCode: {}
  country: {}
phone: {}
electronicMailAddress: {}
onlineUrl: {}
userId: {}
```

So far this function is just a simple wrapper around the extracted `eml_db` database of the slots for all classes from EML package.

Users could fill the R list directly, or maybe serialize it out to a JSON or YAML file and fill that out and then read it back in.  Maybe that is too cumbersome though.
